[package]
name = "riimote"
version = "0.1.0"
authors = ["William Stevens <contact@wastevensv.com>"]

[dependencies]
libc = "0.2.39"

[build-dependencies]
bindgen = "0.33.1"

[lib]
name="riimote_sys"
path="src/lib.rs"
